Populate rep
ebi-gene-expression-group/atlas-deconvolution-references pull request #1
Opened 2023-03-27 16:16 UTC by nadjano

Populated rep with scripts, envs and Snakefile to create reference library at $DECONV_REF. For running pipeline,  run_deconvolution_reference_creation.sh with configuration variables and config.yaml with scxa accessions is required.
It should be possible to create these references for any scxa accession with cell type ontology labels and organism part ontology labels, but we have to manually decide which accession make sense to include. 

Main steps of the pipeline are:
- copy input files for ANND and non ANND experiments (this is still a bit problematic for ANND accession as they are not completely curated)
- create SeuratObjects per scxa experiment
- split SeuratObjects into organism.parts (if multiple)
- reduce number of cell types (if too many)
- create three kind of references per SeuratObject which are required by the deconvolution tools
- scale one of these references (input for DWLS)
- plot UMAPs to visualise references and check cell type label reduction
- make a summary file of which references where created from which accession

The output of this pipeline are therefore:
- deconvolution reference lib with three files per scxa accession + organism part
- one summary file
- one png file  per scxa accession + organism part with two UMAP plots for quality control

It can happen that more than one of the scxa experiments has a specific organism part, therefore we must decide from which scxa experiment the reference looks better (in terms of number of cells, cell type labels ...). To exclude organism parts from accessions they can be included in the config.yaml to avoid them being created.

2023-03-29 14:04 UTC, pmb59 requested changes
Hi @nadjano  
This is looking great. Mostly I have minor comments to improve formatting and style.

If you have intermediate files that are not needed, I would suggest you mark them as `temp()` so Snakemake can delete when non necessary

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +        config['deconv_ref'] + '/homo_sapiens_summary.tsv'
the species here is hardcoded. Could we specify and get also from the config file? In case we want to run for other organisms , such as mus_musculus

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +#Rule for copying all the project anndatafiles we want to build references from
```suggestion
# Rule for copying all the project anndata files we want to build references from
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +    Max number attemps = 8
it doesn't seem to be 8

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +#Rule all
```suggestion
# Rule all
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +            cp {input} scxa_input/{wildcards.experiment}
the `cp` command is the same. Why do you need the if/else?

2023-03-29 14:04 UTC, pmb59 commented on README.md
> +```
Probably you could comment about the outputs.

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +        """
Please consider adding this to the rules
```suggestion
        """
        set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
        exec &> "{log}"
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +#Rule for creating SeuratObjects for anndata and non anndata experiments
```suggestion
# Rule for creating SeuratObjects for anndata and non anndata experiments
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +rule splitByTissue:
Please consider adding info like this instead of outer comment
```suggestion
rule splitByTissue:
    """
    Rule to split sc reference into single organism parts.
    """
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +        "envs/scONTO.yaml"
please consider having the conda env definition first in each rule

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +rule generateReferences:
Please explain a bit in the commented part what are the different outputs (C0, C1, phenData)
```suggestion
rule generateReferences:
    """
    Rule to generate different kind of references from the SeuratObject
    """
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +rule scale_C:
could you please rename the rules in a way that the name is more informative (instead of `scale_C`)?
```suggestion
rule scale_C:
    """
    Rule to scale sc references. Scaling process consist of ... 
    """
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +        config['deconv_ref'] + '/homo_sapiens_summary.tsv'
the species here is hardcoded. Could we specify and get also from the config file? In case we want to run for other organisms , such as mus_musculus

2023-03-29 14:04 UTC, pmb59 commented on envs/TissueSplit.yaml
> +  - r-seurat
maybe you can pin Seurat to be a version `>=` than the one you are currently using?

2023-03-29 14:04 UTC, pmb59 commented on envs/UMAPplot.yaml
> +
It is fine to get rid of these spaces
```suggestion
```

2023-03-29 14:04 UTC, pmb59 commented on envs/env.yaml
> +name: decon_convert
the name of this file is `env.yaml`, probably should be changed

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +obo_file = 'deconvolution-reference-library/files/basic.obo' #download here: http://purl.obolibrary.org/obo/uberon/basic.obo
please add to the README how you generated the 2 `.obo` files

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +##
```suggestion
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +devtools::install_github('cellgeni/sceasy')
I assume this can not be added to the conda env.

In that case, you don't want to install every time in the environment, but check first. Something like:

```
if (!require("pacman")) install.packages("pacman")
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +C = CreateSeuratObject(counts = counts, meta.data = metadata)
please consider renaming following valriables
```
filename_O 
C
t
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +args <- commandArgs(trailingOnly = TRUE)
You can add a check here:
```suggestion
args <- commandArgs(trailingOnly = TRUE)

if(length(args) != 1) {
   stop("Not correct number of arguments. Please supply 1 argument")
}
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +#create SeuratObject
```suggestion
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +            Rscript {workflow.basedir}/scripts/convert.R {wildcards.experiment}
`convert.R` is not very informative , please rename script

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +#rename colum names. If "inferred_cell_type_._ontology_labels_ontology" is
```suggestion
# rename colum names. If "inferred_cell_type_._ontology_labels_ontology" is 
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/convert.R
> +# we want to extract the UBERON ids from the links --> basename
what if any is present?

2023-03-29 14:04 UTC, pmb59 commented on scripts/createSeuratObject.R
> +
```suggestion
if(length(args) != 1) {
   stop("Not correct number of arguments. Please supply 1 argument")
}
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/createSeuratObject.R
> +filename_O = paste0('scxa_input/',sample,'/', sample, '.project_seurat.rds')
again, please find better names for the variables

2023-03-29 14:04 UTC, pmb59 commented on scripts/genRef_1.R
> +## @zgr2788
?

2023-03-29 14:04 UTC, pmb59 commented on scripts/genRef_1.R
> +args <- commandArgs(trailingOnly = TRUE)
```suggestion
args <- commandArgs(trailingOnly = TRUE)
if(length(args) != 2) {
   stop("Not correct number of arguments. Please supply 2 arguments")
}

```

2023-03-29 14:04 UTC, pmb59 commented on scripts/genRef_1.R
> +## Reference matrix type 1 (rows = genenames, cols = celltypes) generation script
I think you should add this in all your R scripts
```suggestion
#!/usr/bin/env Rscript

## Reference matrix type 1 (rows = genenames, cols = celltypes) generation script
```

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +        method = "none"
this needs some explanation too. Why is it always "none"?

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +### script to create a summary file of all the organism part references we created
```suggestion

### script to create a summary file of all the organism part references we created
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/genRef_1.R
> +)
R scripts can benefit from a style formatting. Example:
```suggestion
switch(transform,
  "none" = {
    message('Warning: No transformation applied')
  },
  "log" = {
    C_0@assays$RNA@counts <- log1p(C_0@assays$RNA@counts)
  },
  "sqrt" = {
    C_0@assays$RNA@counts <- sqrt(C_0@assays$RNA@counts)
  },
  "vst" = {  # do not use
    message('Warning: varianceStabilizingTransformation requires high memory and is not recommended.')
    C_0@assays$RNA@counts <- round(C_0@assays$RNA@counts)
    C_0@assays$RNA@counts <- DESeq2::varianceStabilizingTransformation(C_0@assays$RNA@counts)
  }
)

```

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +devtools::install_github("YY-SONG0718/scOntoMatch")
```suggestion
if (!require("scOntoMatch")) devtools::install_github("YY-SONG0718/scOntoMatch")
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +
check here number of argument is correct - stop if not

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +              outfile, sep = "\t", row.names = FALSE, col.names = TRUE)
```suggestion
write.table(data.frame(
  Accession = character(),
  UBERON_ID = character(),
  organism_part = character(),
  date = character()
  ), 
  outfile, sep = "\t", row.names = FALSE, col.names = TRUE)
```
This makes it easier to see the column names and the values being passed to data.frame().

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +#read in UBERON ontologys to translate UBERON ids to organism part labels
```suggestion
# read in UBERON ontologies to translate UBERON ids to organism part labels
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +# Load required packages
```suggestion
```
when comments are very obvious, better remove

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeSummary.R
> +#append the summary file for all the references
```suggestion
# append the summary file for all the references
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeUMAPplots.R
> +p1 = DimPlot(seurat_obj,
Please use `<-` instead of `=` in the R scripts
```suggestion
p1 <- DimPlot(seurat_obj, 
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/makeUMAPplots.R
> +seurat_obj <- RunUMAP(seurat_obj, dims = 1:10)
these steps around can require significan memory if you have many cells.

Maybe let the `get_mem_mb` go to few attempts (reiterations)

2023-03-29 14:04 UTC, pmb59 commented on scripts/reduceCellTypes.R
> +suppressMessages(devtools::install_github("YY-SONG0718/scOntoMatch"))
```suggestion

# Load required packages
suppressMessages(library(devtools))
if (!require("scOntoMatch")) devtools::install_github("YY-SONG0718/scOntoMatch")
suppressMessages(library(scOntoMatch))
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/reduceCellTypes.R
> +additional_ontologies = unlist(ont$children, use.names = F)
```suggestion
additional_ontologies <- unlist(ont$children, use.names = FALSE)
```

2023-03-29 14:04 UTC, pmb59 commented on scripts/splitIntoTissues.R
> +                          y = seurat_downsampled[2:length(cell_types)] )
```suggestion
seurat_downsampled = merge(
  seurat_downsampled[[1]],
  y = seurat_downsampled[2:length(cell_types)]
)
```

2023-03-29 14:04 UTC, pmb59 commented on README.md
> +```
If you are using any code from https://github.com/Functional-Genomics/CATD_snakemake , it would be good add a reference in the end of the README

2023-03-29 14:04 UTC, pmb59 commented on Snakefile
> +configfile: 'config.yaml'
Maybe you could add a simple example of this file in the repo..

2023-03-29 14:04 UTC, pmb59 commented on README.md
> +Snakemake workflow to generate single-cell reference dataset for deconvolution in Atlas
```suggestion
Snakemake workflow to generate single-cell reference dataset for bulk RNA-seq deconvolution in Atlas
```

2023-03-29 14:16 UTC, nadjano commented on Snakefile
> +            cp {input} scxa_input/{wildcards.experiment}
Thats ture!

2023-03-29 14:19 UTC, nadjano commented on Snakefile
> +configfile: 'config.yaml'
Yes, added 'example.config'

2023-05-04 08:47 UTC, pmb59 commented on README.md
> +Folowing scripts are taken from the [CATD_snakemake pipeline](https://github.com/Functional-Genomics/CATD_snakemake) which benchmarks deconvolution methods:
```suggestion
The following scripts are taken from the [CATD_snakemake pipeline](https://github.com/Functional-Genomics/CATD_snakemake) which benchmarks deconvolution methods:
```

2023-05-04 08:47 UTC, pmb59 commented on Snakefile
> +##
```suggestion
```

2023-07-20 10:11 UTC, pmb59 approved these changes
LGTM @nadjano !

thanks for addressing my comments

2023-07-20 10:12 UTC, merged